# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 09:19
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=users.models.IntegerRangeField(default=0),
        ),
    ]
