# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='note_avg',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
    ]
