# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161231_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Uploaded image'),
        ),
    ]
