# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Swapp API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /items:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets unarchived `Item` objects.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: q
          in: query
          description: Query of user
          required: false
          type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfItems
            type: array
            items:
              title: Item
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                creation_date:
                  type: string
                image_url:
                  type: string
                category:
                  type: string
                city:
                  type: string
                country:
                  type: string
                offer_received:
                  type: number
                views:
                  type: number
                comments:
                  type: number
                likes:
                  type: number
                owner_image_url:
                  type: string
                  
  # This is a path endpoint. Change it.
  /items/{id}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets a detailed unarchived `Item` object.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: id
          in: path
          description: id of the item
          required: true
          type: number
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ObjectDetail
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              description:
                type: string
              price_min:
                type: number
              price_max:
                type: number
              creation_date:
                type: string
              condition:
                type: string
              brand:
                type: string
              color:
                type: string
              owner:
                title: Owner
                type: object
                properties:
                  id:
                    type: number
                  profile_picture_url:
                    type: string
                  inventory:
                    type: array
                    properties:
                      item_image_url:
                        type: string
                  score:
                    type: number
                  number_of_vote:
                    type: number
                  interests:
                    type: array
                    properties:
                      item:
                        type: string
                  delivery_address:
                    type: string
                  delivery_methods:
                    type: array
                    properties:
                      method:
                        type: string
              category:
                title: Category
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
              comments:
                type: array
                properties:
                  comment:
                    type: object
                    properties:
                      user_id:
                        type: number
                      user_profile_picture_url:
                        type: string
                      user_fullname:
                        type: string
                      date:
                        type: string
                      content:
                        type: string
              similars:
                type: array
                properties:
                  image_url:
                    type: string
                    