# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_methods',
            field=models.ManyToManyField(to='items.DeliveryMethod'),
        ),
    ]
