# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('status', models.BooleanField()),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
