# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('status', models.BooleanField()),
                ('comment', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('item_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_done', to='items.Item')),
                ('item_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='items.Item')),
            ],
        ),
    ]
