# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
