# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
