# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20161114_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
