# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170106_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
