# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20161130_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
