# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170104_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinfo',
            name='info',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='keyinfo',
            name='key',
            field=models.CharField(max_length=30),
        ),
    ]
